# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install dependencies
      run: go get ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: make linux
    
    - uses: actions/upload-artifact@v4
      with:
        name: ovpn-ldap-auth
        path: |
          ./target/linux_amd64/ovpn-ldap-auth.linux-amd64.tar.gz
          ./target/linux_amd64/sha256sum.txt
        if-no-files-found: error
